### ISSUE TITLE
Short transcription is not saving for flutter JWT Expires Error 401

### ISSUE THREAD

**Issue by surajsahani** [navgurukul/oscar_ai_transcription#8]

**Comment by surajsahani** [comment]
Log file analysis required to identify the cause of 401 errors post-save added attachment for same @shalini8979 .

**Comment by surajsahani** [comment]
![Screenshot 2024-11-22 at 2 56 07 PM](https://github.com/user-attachments/assets/3c426b19-0d66-4732-8fb7-b8f35efb7bf4)

**Comment by shalini8979** [comment]
Please provide the inputs which you use here while recording

**Comment by Jayshri15** [comment]
It's resolved.
